### ISSUE TITLE
Error in debug logging despite the HA call being successful

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#104]
I have in a script the call `homeassistant.toggle(entity_id='switch.michael_bureau_gauche')`. The call is successful - the switch is toggled.

I see, however, that in the debug log (`pyscript` level is set to debug) I see some kind of error with the logging:

```
2020-12-01 13:37:35 DEBUG (MainThread) [custom_components.pyscript.eval] file.zigbee_rf433.message_zigbee: calling debug("switch.michael_bureau_gauche", "toggle", {})
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/site-packages/colorlog/colorlog.py", line 123, in format
    message = super(ColoredFormatter, self).format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: 'switch.michael_bureau_gauche'
Arguments: ('toggle',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
Message: 'switch.michael_bureau_gauche'
Arguments: ('toggle',)
2020-12-01 13:37:35 DEBUG (MainThread) [custom_components.pyscript.eval] file.zigbee_rf433.message_zigbee: calling toggle(, {'entity_id': 'switch.michael_bureau_gauche'})
```

**Comment by dlashua** [comment]
Can you share the entire `message_zigbee` function as well as any decorators on it? I think there's something else generating this debug message.

**Comment by wsw70** [comment]
> Can you share the entire message_zigbee function as well as any decorators on it? I think there's something else generating this debug message.

Here is it is (it is draft state as a direct port from AppDaemon so tests and railguards are still missing). `get_config()` reads a YAML config from a string and returns a dict.

```
@service
def message_zigbee(**data):
    config = get_config()
    device = data['topic'].split('/')[1]
    # check if device is registered
    if device in config['zigbee']:
        log.debug(f"found device {device}")
        actions(config['zigbee'][device][data['payload']])
    else:
        log.warning(f"unknown Zigbee switch {device}")


def actions(what):
    for light in what:
        # get the action to do for that light
        target, action = light.split(',')
        log.debug(target, action)
        if action == "on":
            homeassistant.turn_on(entity_id=target)
        elif action == "off":
            homeassistant.turn_off(entity_id=target)
        elif action == "toggle":
            homeassistant.toggle(entity_id=target)
        else:
            log.warning(f"unknown action {action} for {target}")
```

**Comment by wsw70** [comment]
OK found the error: `log.debug(target, action)`.

Sory for the disturbance.
