### ISSUE TITLE
Pyscript won't load with HASS 2023.08.01

### ISSUE THREAD

**Issue by tal** [custom-components/pyscript#510]
Seems like it's unable to handle the new event type of entity:

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/pyscript/__init__.py:27
Integration: pyscript (documentation, issues)
First occurred: 6:34:44 PM (1 occurrences)
Last logged: 6:34:44 PM

Setup failed for custom integration pyscript: Unable to import component: cannot import name 'Event' from 'homeassistant.helpers.event' (/usr/src/homeassistant/homeassistant/helpers/event.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/pyscript/__init__.py", line 27, in <module>
    from homeassistant.helpers.event import Event as HAEvent
ImportError: cannot import name 'Event' from 'homeassistant.helpers.event' (/usr/src/homeassistant/homeassistant/helpers/event.py)
```

**Comment by craigbarratt** [comment]
Duplicates #500, #501, #502, #504, #505.  Upgrade to pyscript 1.5.0.

**Comment by r0oland** [comment]
I am on Home Assistant 2023.8.1 running in a Docker Container and using pyscript 1.5.0 and I am still having issues:
```
[homeassistant.setup] Setup failed for custom integration pyscript: Unable to import component: cannot import name 'Event' from 'homeassistant.helpers.event' (/usr/src/homeassistant/homeassistant/helpers/event.py)
```

The relevant part of the log can be found attached.

I have restarted everything, pulled the latest Docker container and reinstalled pyscript, all with no effect. Any suggestions on what to try? 


[home-assistant_2023-08-11T06-15-51.953Z.log](https://github.com/custom-components/pyscript/files/12318994/home-assistant_2023-08-11T06-15-51.953Z.log)

**Comment by craigbarratt** [comment]
Please upgrade to pyscript 1.5.0.

**Comment by r0oland** [comment]
Thanks for the super quick reply!

See attached manifest (renamed to txt for Github upload). 1.5.0...

And yes, the import is in the init file (line 27):
![image](https://github.com/custom-components/pyscript/assets/558053/d4f19b5f-3101-4cf4-8c83-6817c565495d)


[manifest.txt](https://github.com/custom-components/pyscript/files/12319064/manifest.txt)

**Comment by r0oland** [comment]
I am sorry...of course the error was on my side...
For some reason, there where two copies of pyscript in the custom components directory:
- "pyscript"
- "pyscript_old"

For some reason it would automatically pick the old one...

After deleting that things seem to be running normally...

**Comment by craigbarratt** [comment]
Yes, that is 1.5.0.

However, from the log file, you can see the error is coming from this file: `/config/custom_components/pyscript_old/__init__.py`, which presumably is an old version, I would guess manually copied?

**Comment by Nxt3** [comment]
I'm getting the same error but I don't have a `pyscript_old`

<img width="1460" alt="Screenshot 2023-08-21 at 12 49 52 PM" src="https://github.com/custom-components/pyscript/assets/2940826/d5aa9e17-b335-40e7-8d0f-4a11d0ae3db8">
