### ISSUE TITLE
@service crashs homeassistant

### ISSUE THREAD

**Issue by littleyoda** [custom-components/pyscript#517]
After updating HA to the latest version (2023.8.3) from 2023.7, HA did not start.
I had to disable all pyscripts to get it to run at all.
After a lot of testing, it turns out that the @service statement is the problem.

The following statement runed from jupyter, leads to HA being unstable. HA seems to run, but no longer accepts new browser connections. I've to restart HA.
```
@service("halloworldtest.run")
def myTestTrigger():
    print("Hallo World")
```

```
2023-08-20 19:33:50.097 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140134801655744] Error handling message: Unknown error (unknown_error) <NAME REMOVED> from <IP REMOVED> (Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 417, in handle_get_services
    payload = await _async_get_all_descriptions_json(hass)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 398, in _async_get_all_descriptions_json
    descriptions = await async_get_all_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 612, in async_get_all_descriptions
    translations = await translation.async_get_translations(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 318, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 209, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 230, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'halloworldtest' not found.
```

**Comment by craigbarratt** [comment]
I tried 2023.8.3 with your service example and it works fine for me.  I'm not sure why it is crashing in your case.

**Comment by Kaptensanders** [comment]
Same problem for me. HA 2023.8.3, core install on venv - Python 3.11.4
Exact same error as @littleyoda

**Comment by littleyoda** [comment]
can confirm the workaround of Kaptensanders. 
@service works
@service("xxyz"), however, does not works.

**Comment by craigbarratt** [comment]
Ok, the issue is this code [`homeassistant/helpers/service.py`](https://github.com/home-assistant/core/blob/588db501fbf11aedecd549540661397557916e35/homeassistant/helpers/service.py#L612) got added in  in 2023.8.0.  HASS now loads all translations for all services.  When an arbitrary service name isn't part of an associated integration, the loading of translations fails.  That causes `async_get_all_descriptions()` to fail.

I can't see a work around for this.  Perhaps it's a breaking change, and you can only create services in `pyscript` that are part of an existing integration (ie, top-level name)?

**Comment by Kaptensanders** [comment]
> The issue is this code [`homeassistant/helpers/service.py`](https://github.com/home-assistant/core/blob/588db501fbf11aedecd549540661397557916e35/homeassistant/helpers/service.py#L612) got added in in 2023.8.0. HASS now loads all translations for all services. When an arbitrary service name isn't part of an associated integration, the loading of translations fails. That causes `async_get_all_descriptions()` to fail.
> 
> I can't see a work around for this. Perhaps it's a breaking change, and you can only create services in `pyscript` that are part of an existing integration (ie, top-level name)?

Actually naming a service still works if no non-existing integration is specified (top level).
Maybe this is actually more appropriate than inventing integrations that does not exist. 

`@service(f"service_name") # works and service name will become pyscript.service_name.`

**Comment by Kaptensanders** [comment]
Breaking change maybe but an ok one. When you think about it It is maybe bad practice to refer to non-existing integrations. Not surprising that could lead to problems with HA.

`@service("service_name") # works fine and the service will be pyscript.service_name    `
