### ISSUE TITLE
Upgrading pytest-homeassistant-custom-component to 0.0.20

### ISSUE THREAD

**Issue by craigbarratt** [custom-components/pyscript#93]
@raman325 - I was looking at upgrading `pytest-homeassistant-custom-component` from 0.0.8 to 0.0.20.  That requires a few other upgrades, including these in `tests/requirements_test.txt`:
```
coverage==5.3
pre-commit==2.8.2
pytest==6.1.2
```
After adding an empty `custom_components/__init__.py` file (see [this issue](https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/issues/23)), all the tests run except `tests/test_apps_modules.py` which stalls without any error until you hit `^C`.

Would you mind seeing what's wrong with `tests/test_apps_modules.py`?

Once it runs cleanly then I'll update `tests/requirements_test.txt`.

Thanks!

**Comment by raman325** [comment]
To be quite honest with you, at first glance I don't see anything wrong. I also looked at the diff between 0.0.8 and 0.0.20 and nothing sticks out: https://github.com/MatthewFlamm/pytest-homeassistant-custom-component/compare/v0.0.8...0.0.20 I will try to look at this in the upcoming weekend, this week is tough due to Thanksgiving

**Comment by balloob** [comment]
Run the test suite with `pytest --timeout=2 tests` and you will see exactly where it was hanging. Common cause for hanging tests is calling a sync method from async context.

**Comment by raman325** [comment]
Thanks @balloob I am seeing the same exception I saw last night which is an `UnknownHandler` exception. I don't understand why that's occurring or why it's blocking there - the other test files use the exact same logic to setup the component and they don't seem to have the same issue.

```txt
$ pytest --timeout=2 tests/test_apps_modules.py --verbose
Test session starts (platform: darwin, Python 3.9.0, pytest 6.1.2, pytest-sugar 0.9.4)
cachedir: .pytest_cache
rootdir: /Users/raman/projects/pyscript, configfile: setup.cfg
plugins: sugar-0.9.4, requests-mock-1.8.0, xdist-2.1.0, homeassistant-custom-component-0.0.20, cov-2.10.1, aiohttp-0.3.0, timeout-1.4.2, forked-1.3.0, test-groups-1.0.3
timeout: 2.0s
timeout method: signal
timeout func_only: False
collecting ...

―――――――――――――――――――――――――――――――――――――――――――――――――――――――― test_service_exists[pyloop] ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――

pyfuncitem = <Function test_service_exists[pyloop]>

    def pytest_pyfunc_call(pyfuncitem):  # type: ignore
        """
        Run coroutines in an event loop instead of a normal function call.
        """
        fast = pyfuncitem.config.getoption("--aiohttp-fast")
        if asyncio.iscoroutinefunction(pyfuncitem.function):
            existing_loop = pyfuncitem.funcargs.get('proactor_loop')\
                or pyfuncitem.funcargs.get('loop', None)
            with _runtime_warning_context():
                with _passthrough_loop_context(existing_loop, fast=fast) as _loop:
                    testargs = {arg: pyfuncitem.funcargs[arg]
                                for arg in pyfuncitem._fixtureinfo.argnames}
>                   _loop.run_until_complete(pyfuncitem.obj(**testargs))

venv/lib/python3.9/site-packages/aiohttp/pytest_plugin.py:170:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:629: in run_until_complete
    self.run_forever()
/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:596: in run_forever
    self._run_once()
/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:1854: in _run_once
    event_list = self._selector.select(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selectors.KqueueSelector object at 0x10a17d5b0>, timeout = 899.9837486721328

    def select(self, timeout=None):
        timeout = None if timeout is None else max(timeout, 0)
        # If max_ev is 0, kqueue will ignore the timeout. For consistent
        # behavior with the other selector classes, we prevent that here
        # (using max). See https://bugs.python.org/issue29255
        max_ev = max(len(self._fd_to_key), 1)
        ready = []
        try:
>           kev_list = self._selector.control(None, max_ev, timeout)
E           Failed: Timeout >2.0s

/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py:562: Failed
----------------------------------------------------------- Captured stderr setup ------------------------------------------------------------
DEBUG:asyncio:Using selector: KqueueSelector
------------------------------------------------------------ Captured stderr call ------------------------------------------------------------
INFO:homeassistant.loader:Loaded pyscript from custom_components.pyscript
WARNING:homeassistant.loader:You are using a custom integration for pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
INFO:homeassistant.setup:Setting up pyscript
DEBUG:homeassistant.helpers.restore_state:Not creating cache - no saved states found
INFO:homeassistant.setup:Setup of domain pyscript took 0.0 seconds
DEBUG:homeassistant.helpers.restore_state:Dumping states
INFO:pytest_homeassistant_custom_component.common:Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~ Stack of SyncWorker_1 (123145590939648) ~~~~~~~~~~~~~~~~~~~~
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 75, in _worker
    work_item = work_queue.get(block=True)

~~~~~~~~~~~~~~~~~~~ Stack of SyncWorker_0 (123145574150144) ~~~~~~~~~~~~~~~~~~~~
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 75, in _worker
    work_item = work_queue.get(block=True)

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
------------------------------------------------------------- Captured log call --------------------------------------------------------------
INFO     homeassistant.loader:loader.py:290 Loaded pyscript from custom_components.pyscript
WARNING  homeassistant.loader:loader.py:463 You are using a custom integration for pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
INFO     homeassistant.setup:setup.py:183 Setting up pyscript
INFO     homeassistant.setup:setup.py:232 Setup of domain pyscript took 0.0 seconds
INFO     pytest_homeassistant_custom_component.common:common.py:935 Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}



―――――――――――――――――――――――――――――――――――――――――――――― ERROR at teardown of test_service_exists[pyloop] ――――――――――――――――――――――――――――――――――――――――――――――

loop = <_UnixSelectorEventLoop running=False closed=True debug=False>
hass_storage = {'core.restore_state': {'data': [], 'key': 'core.restore_state', 'version': 1}}
request = <SubRequest 'hass' for <Function test_service_exists[pyloop]>>

    @pytest.fixture
    def hass(loop, hass_storage, request):
        """Fixture to provide a test instance of Home Assistant."""

        def exc_handle(loop, context):
            """Handle exceptions by rethrowing them, which will fail the test."""
            # Most of these contexts will contain an exception, but not all.
            # The docs note the key as "optional"
            # See https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_exception_handler
            if "exception" in context:
                exceptions.append(context["exception"])
            else:
                exceptions.append(
                    Exception(
                        "Received exception handler without exception, but with message: %s"
                        % context["message"]
                    )
                )
            orig_exception_handler(loop, context)

        exceptions = []
        hass = loop.run_until_complete(async_test_home_assistant(loop))
        orig_exception_handler = loop.get_exception_handler()
        loop.set_exception_handler(exc_handle)

        yield hass

        loop.run_until_complete(hass.async_stop(force=True))
        for ex in exceptions:
            if (
                request.module.__name__,
                request.function.__name__,
            ) in IGNORE_UNCAUGHT_EXCEPTIONS:
                continue
            if isinstance(ex, ServiceNotFound):
                continue
>           raise ex

venv/lib/python3.9/site-packages/pytest_homeassistant_custom_component/plugins.py:146:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.9/site-packages/homeassistant/data_entry_flow.py:117: in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <homeassistant.config_entries.ConfigEntriesFlowManager object at 0x108d03c40>, handler_key = 'pyscript'

    async def async_create_flow(
        self, handler_key: Any, *, context: Optional[Dict] = None, data: Any = None
    ) -> "ConfigFlow":
        """Create a flow for specified handler.

        Handler key is the domain of the component that we want to set up.
        """
        try:
            integration = await loader.async_get_integration(self.hass, handler_key)
        except loader.IntegrationNotFound as err:
            _LOGGER.error("Cannot find integration %s", handler_key)
            raise data_entry_flow.UnknownHandler from err

        # Make sure requirements and dependencies of component are resolved
        await async_process_deps_reqs(self.hass, self._hass_config, integration)

        try:
            integration.get_platform("config_flow")
        except ImportError as err:
            _LOGGER.error(
                "Error occurred loading configuration flow for integration %s: %s",
                handler_key,
                err,
            )
            raise data_entry_flow.UnknownHandler

        handler = HANDLERS.get(handler_key)

        if handler is None:
>           raise data_entry_flow.UnknownHandler
E           homeassistant.data_entry_flow.UnknownHandler

venv/lib/python3.9/site-packages/homeassistant/config_entries.py:545: UnknownHandler
----------------------------------------------------------- Captured stderr setup ------------------------------------------------------------
DEBUG:asyncio:Using selector: KqueueSelector
------------------------------------------------------------ Captured stderr call ------------------------------------------------------------
INFO:homeassistant.loader:Loaded pyscript from custom_components.pyscript
WARNING:homeassistant.loader:You are using a custom integration for pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
INFO:homeassistant.setup:Setting up pyscript
DEBUG:homeassistant.helpers.restore_state:Not creating cache - no saved states found
INFO:homeassistant.setup:Setup of domain pyscript took 0.0 seconds
DEBUG:homeassistant.helpers.restore_state:Dumping states
INFO:pytest_homeassistant_custom_component.common:Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~ Stack of SyncWorker_1 (123145590939648) ~~~~~~~~~~~~~~~~~~~~
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 75, in _worker
    work_item = work_queue.get(block=True)

~~~~~~~~~~~~~~~~~~~ Stack of SyncWorker_0 (123145574150144) ~~~~~~~~~~~~~~~~~~~~
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 908, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 75, in _worker
    work_item = work_queue.get(block=True)

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
------------------------------------------------------------- Captured log call --------------------------------------------------------------
INFO     homeassistant.loader:loader.py:290 Loaded pyscript from custom_components.pyscript
WARNING  homeassistant.loader:loader.py:463 You are using a custom integration for pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
INFO     homeassistant.setup:setup.py:183 Setting up pyscript
INFO     homeassistant.setup:setup.py:232 Setup of domain pyscript took 0.0 seconds
INFO     pytest_homeassistant_custom_component.common:common.py:935 Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}
---------------------------------------------------------- Captured stderr teardown ----------------------------------------------------------
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_stop[L]>
ERROR:homeassistant:Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/raman/projects/pyscript/venv/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 117, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/Users/raman/projects/pyscript/venv/lib/python3.9/site-packages/homeassistant/config_entries.py", line 545, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
DEBUG:homeassistant.helpers.restore_state:Dumping states
DEBUG:homeassistant.core:Waited 60 seconds for task: <Task pending name='Task-3' coro=<_async_setup_component() running at /Users/raman/projects/pyscript/venv/lib/python3.9/site-packages/homeassistant/setup.py:248> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10a21d490>()]> cb=[<TaskWakeupMethWrapper object at 0x10a200910>()]>
WARNING:homeassistant.core:Timed out waiting for shutdown stage 1 to complete, the shutdown will continue
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_final_write[L]>
INFO:pytest_homeassistant_custom_component.common:Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}
DEBUG:homeassistant.core:Bus:Handling <Event homeassistant_close[L]>
----------------------------------------------------------- Captured log teardown ------------------------------------------------------------
ERROR    homeassistant:runner.py:115 Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/raman/projects/pyscript/venv/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 117, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/Users/raman/projects/pyscript/venv/lib/python3.9/site-packages/homeassistant/config_entries.py", line 545, in async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
WARNING  homeassistant.core:core.py:536 Timed out waiting for shutdown stage 1 to complete, the shutdown will continue
INFO     pytest_homeassistant_custom_component.common:common.py:935 Writing data to core.restore_state: {'version': 1, 'key': 'core.restore_state', 'data': []}
                                                                                                                               100% ██████████
========================================================== short test summary info ===========================================================
FAILED tests/test_apps_modules.py::test_service_exists[pyloop] - Failed: Timeout >2.0s
FAILED tests/test_apps_modules.py::test_service_exists[pyloop] - homeassistant.data_entry_flow.UnknownHandler

Results (123.16s):
       1 failed
         - tests/test_apps_modules.py:20 test_service_exists[pyloop]
       1 error
```

**Comment by balloob** [comment]
Oh, just import the config flow platform before running the test.

**Comment by balloob** [comment]
This only happens if you don't use the normal way of instantiating a config flow btw.

**Comment by raman325** [comment]
I tried instantiating a config flow by running `hass.config_entries.flow.async_init` but hit the same error. Am I missing something?

**Comment by craigbarratt** [comment]
Thanks @balloob and @raman325!  I pushed a change that patches just `custom_components.pyscript.global_ctx.open` with `MockOpen()` instead of `builtins.open`, and the test then passes. As you suggest, there's probably a more robust fix.

Anyhow, I'll go ahead and pin `pytest-homeassistant-custom-component` to `0.0.20`, and update `tests/requirements_test.txt`.

**Comment by raman325** [comment]
Ah nevermind, looks like @craigbarratt figured it out. My guess is that your original patch was preventing HA from loading the integration/platforms correctly.

**Comment by craigbarratt** [comment]
Yes, that makes sense.  It was probably the root cause.  Sorry to bother you.

**Comment by raman325** [comment]
All good glad you got it resolved

**Comment by balloob** [comment]
Home Assistant needs to load manifests etc. Generally, avoid mocking `builtins` and do what you did here instead 👍
